name: Quick Submit

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  run-scenario:
    if: startsWith(github.head_ref, 'quick-submit-')
    uses: ./.github/workflows/quick-submit-runner.yml
    permissions:
      id-token: write
      contents: write
      packages: read
    with:
      num_shards: 10
    secrets:
      GREEN_SECRETS_JSON: >-
        {"hf_token":${{ toJSON(secrets.OFFICEQA_PRO_V2_HF_TOKEN) }}}
